issue #27
airbnb/react-outside-click-handler pull request #28
Opened 2019-06-06 00:36 UTC by nathanmmiller

Allow "inline" to be set as display property.

2019-06-12 05:43 UTC, ljharb requested changes
Please add a test for this display value. Thanks!

2019-09-15 11:32 UTC, nathanmmiller commented
@ljharb Just added tests for this display. I note there aren't tests for the other display options, if you're happy with this approach, I'll raise another issue and PR to add tests for the other displays using the same approach.

2019-09-15 14:52 UTC, ljharb approved these changes

2019-09-15 15:06 UTC, merged

2019-09-20 12:53 UTC, nathanmmiller commented
Thanks so much @ljharb! Will there be an npm release that includes these changes so that I can import them in my world?